package newdatabase;
// Generated 2020-01-17 19:30:10 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Nabywca generated by hbm2java
 */
@Entity
@Table(name = "nabywca", catalog = "ivodb")
public class Nabywca implements java.io.Serializable {

	private Integer id;
	private String telefon;
	private String nip;
	private Set<Faktura> fakturas = new HashSet(0);
	private Adres adres;

	public Nabywca() {
	}

	public Nabywca(String telefon, String nip) {
		this.telefon = telefon;
		this.nip = nip;
	}

	public Nabywca(String telefon, String nip, Set<Faktura> fakturas, Adres adres) {
		this.telefon = telefon;
		this.nip = nip;
		this.fakturas = fakturas;
		this.adres = adres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "telefon", nullable = false, length = 20)
	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	@Column(name = "nip", nullable = false, length = 20)
	public String getNip() {
		return this.nip;
	}

	public void setNip(String nip) {
		this.nip = nip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nabywca")
	public Set<Faktura> getFakturas() {
		return this.fakturas;
	}

	public void setFakturas(Set fakturas) {
		this.fakturas = fakturas;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "nabywca")
	public Adres getAdres() {
		return this.adres;
	}

	public void setAdres(Adres adres) {
		this.adres = adres;
	}

}
