package newdatabase;
// Generated 2020-01-17 19:30:10 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vat generated by hbm2java
 */
@Entity
@Table(name = "vat", catalog = "ivodb")
public class Vat implements java.io.Serializable {

	private static final long serialVersionUID = 7827639718863961197L;
	
	private Integer id;
	private String nazwa;
	private long mnoznik;
	private Set<Towar> towars = new HashSet(0);

	public Vat() {
	}

	public Vat(String nazwa, long mnoznik) {
		this.nazwa = nazwa;
		this.mnoznik = mnoznik;
	}

	public Vat(String nazwa, long mnoznik, Set<Towar> towars) {
		this.nazwa = nazwa;
		this.mnoznik = mnoznik;
		this.towars = towars;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nazwa", nullable = false, length = 20)
	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	@Column(name = "mnoznik", nullable = false, precision = 10, scale = 0)
	public long getMnoznik() {
		return this.mnoznik;
	}

	public void setMnoznik(long mnoznik) {
		this.mnoznik = mnoznik;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vat")
	public Set<Towar> getTowars() {
		return this.towars;
	}

	public void setTowars(Set towars) {
		this.towars = towars;
	}

	//@Override
	//public String toString() {
	//	return "Vat [id=" + id + ", nazwa=" + nazwa + ", mnoznik=" + mnoznik + "]";
	//}

}
